// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UIAutomationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SignupCreationFeature : object, Xunit.IClassFixture<SignupCreationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SignupCreation.feature"
#line hidden
        
        public SignupCreationFeature(SignupCreationFeature.FixtureData fixtureData, UIAutomationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SignupCreation", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creating signups for the organisations of type Admin, Advisor, Advocate, Issuer, " +
            "Institutional investor and Private investor that were created in Scenario 1")]
        [Xunit.TraitAttribute("FeatureTitle", "SignupCreation")]
        [Xunit.TraitAttribute("Description", "Creating signups for the organisations of type Admin, Advisor, Advocate, Issuer, " +
            "Institutional investor and Private investor that were created in Scenario 1")]
        [Xunit.TraitAttribute("Category", "LoginRequired")]
        public void CreatingSignupsForTheOrganisationsOfTypeAdminAdvisorAdvocateIssuerInstitutionalInvestorAndPrivateInvestorThatWereCreatedInScenario1()
        {
            string[] tagsOfScenario = new string[] {
                    "LoginRequired"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating signups for the organisations of type Admin, Advisor, Advocate, Issuer, " +
                    "Institutional investor and Private investor that were created in Scenario 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given("User navigates to the signup management page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "organisationType",
                            "Role",
                            "FirstName",
                            "LastName"});
                table2.AddRow(new string[] {
                            "Advisor",
                            "Advisor corporate",
                            "Adv",
                            "isor"});
                table2.AddRow(new string[] {
                            "Advocate",
                            "Advocate",
                            "Advo",
                            "cate"});
                table2.AddRow(new string[] {
                            "Issuer",
                            "Issuer",
                            "Iss",
                            "user"});
                table2.AddRow(new string[] {
                            "Admin",
                            "Administrator",
                            "Adm",
                            "in"});
                table2.AddRow(new string[] {
                            "Institutional Investor",
                            "Bidder",
                            "Institutional",
                            "investor"});
                table2.AddRow(new string[] {
                            "Private Investor",
                            "Bidder",
                            "Private",
                            "investor"});
#line 8
 testRunner.When("User clicks on Create user button and then enters organisation name and type and " +
                        "click on save button", ((string)(null)), table2, "When ");
#line hidden
#line 16
 testRunner.Then("The signup is created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SignupCreationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SignupCreationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
